version: '3'
services:

    api_gateway:
        build: ./api_gateway
        ports:
            - "80:80"
        networks:
            - soa_network
        env_file:
            - ./api_gateway/.env
        depends_on:
            - rabbitmq
            - frontend
            - user_service
            - post_service
            - notification_service
            - chat_service
        command: >
            /bin/bash -c "envsubst \"`for v in $$(compgen -v);do printf '$${%s} ' $$v;done`'\"
            < /etc/nginx/conf.d/nginx.conf.template
            > /etc/nginx/conf.d/default.conf
            && nginx -g 'daemon off;'"

############################## 

    rabbitmq:
        image: rabbitmq:3.12-alpine
        ports:
            - "5672:5672"
            - "15672:15672"
        volumes:
            - rabbitmq_data:/var/lib/rabbitmq/
            - rabbitmq_log:/var/log/rabbitmq
        networks:
            - rabbitmq_network

############################## 

    frontend:
        build: ./frontend
        volumes:
            - ./frontend:/app
        ports:
            - "80"
            # Serve vite hot reload on host port 10000
            - "10000:80"
        networks:
            - soa_network

############################## 

    user_postgres:
        image: postgres:15-alpine
        restart: always
        ports:
            - "5432:5432"
        environment:
            - POSTGRES_DB=soa
            - POSTGRES_PASSWORD=admin
        networks:
            - user_network
        volumes:
            - user_db:/var/lib/postgresql

    user_service:
        build: ./user_service
        volumes:
            - ./user_service:/var/www/soa
        ports:
            - "80"
        networks:
            - soa_network
            - user_network
            - rabbitmq_network
        depends_on:
            - user_postgres
        environment:
            - POSTGRES_CONN_STRING=postgres://postgres:admin@user_postgres:5432/soa
            - PORT=80

##############################

    post_postgres:
        image: postgres:15-alpine
        restart: always
        ports:
            - "5433:5432"
        environment:
            - POSTGRES_DB=soa
            - POSTGRES_PASSWORD=admin
        networks:
            - post_network
        volumes:
            - post_db:/var/lib/postgresql

    post_service:
        build: ./post_service
        volumes:
            - ./post_service:/var/www/soa
        ports:
            - "80"
        networks:
            - soa_network
            - post_network
            - rabbitmq_network
        environment:
            - POSTGRES_CONN_STRING=postgres://postgres:admin@post_postgres:5432/soa
            - PORT=80
        depends_on:
            - post_postgres

##############################

    notification_postgres:
        image: postgres:15-alpine
        restart: always
        ports:
            - "5434:5432"
        environment:
            - POSTGRES_DB=soa
            - POSTGRES_PASSWORD=admin
        networks:
            - notification_network
        volumes:
            - notification_db:/var/lib/postgresql

    notification_service:
        build: ./notification_service
        volumes:
            - ./notification_service:/var/www/soa
        ports:
            - "80"
        networks:
            - soa_network
            - notification_network
            - rabbitmq_network
        environment:
            - POSTGRES_CONN_STRING=postgres://postgres:admin@notification_postgres:5432/soa
            - PORT=80
        depends_on:
            - notification_postgres
        
##############################

    chat_mongodb:
        image: mongo:7-jammy
        restart: always
        ports:
            - "27017:27017"
        environment:
            - MONGO_INITDB_ROOT_USERNAME=root
            - MONGO_INITDB_ROOT_PASSWORD=admin
            - MONGO_INITDB_DATABASE=soa
        networks:
            - chat_network
        volumes:
            - chat_db:/data/db

    chat_service:
        build: ./chat_service
        volumes:
            - ./chat_service:/var/www/soa
        ports:
            - "80"
        networks:
            - soa_network
            - chat_network
            - rabbitmq_network
        environment:
            - MONGO_CONN_STRING=mongodb://root:admin@chat_mongodb:27017
            - PORT=80
        depends_on:
            - chat_mongodb


##############################

networks:
    soa_network:
    user_network:
    post_network:
    notification_network:
    chat_network:
    rabbitmq_network:

volumes:
    user_db:
        driver: local
    post_db:
        driver: local
    notification_db:
        driver: local
    chat_db:
        driver: local
    rabbitmq_data:
        driver: local
    rabbitmq_log:
        driver: local